/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as LauncherRouteImport } from './routes/launcher'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BotsIndexRouteImport } from './routes/bots.index'
import { Route as BoardsIndexRouteImport } from './routes/boards.index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as BotsBotIdRouteImport } from './routes/bots.$botId'
import { Route as BoardsBoardIdRouteImport } from './routes/boards.$boardId'
import { Route as AppsServerIdToolRouteImport } from './routes/apps.$serverId.$tool'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherRoute = LauncherRouteImport.update({
  id: '/launcher',
  path: '/launcher',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsIndexRoute = BotsIndexRouteImport.update({
  id: '/bots/',
  path: '/bots/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsIndexRoute = BoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsBotIdRoute = BotsBotIdRouteImport.update({
  id: '/bots/$botId',
  path: '/bots/$botId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsServerIdToolRoute = AppsServerIdToolRouteImport.update({
  id: '/apps/$serverId/$tool',
  path: '/apps/$serverId/$tool',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/launcher': typeof LauncherRoute
  '/new': typeof NewRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/boards/': typeof BoardsIndexRoute
  '/bots/': typeof BotsIndexRoute
  '/apps/$serverId/$tool': typeof AppsServerIdToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/launcher': typeof LauncherRoute
  '/new': typeof NewRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/boards': typeof BoardsIndexRoute
  '/bots': typeof BotsIndexRoute
  '/apps/$serverId/$tool': typeof AppsServerIdToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/launcher': typeof LauncherRoute
  '/new': typeof NewRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/boards/': typeof BoardsIndexRoute
  '/bots/': typeof BotsIndexRoute
  '/apps/$serverId/$tool': typeof AppsServerIdToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed'
    | '/launcher'
    | '/new'
    | '/boards/$boardId'
    | '/bots/$botId'
    | '/sessions/$sessionId'
    | '/boards/'
    | '/bots/'
    | '/apps/$serverId/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed'
    | '/launcher'
    | '/new'
    | '/boards/$boardId'
    | '/bots/$botId'
    | '/sessions/$sessionId'
    | '/boards'
    | '/bots'
    | '/apps/$serverId/$tool'
  id:
    | '__root__'
    | '/'
    | '/feed'
    | '/launcher'
    | '/new'
    | '/boards/$boardId'
    | '/bots/$botId'
    | '/sessions/$sessionId'
    | '/boards/'
    | '/bots/'
    | '/apps/$serverId/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedRoute: typeof FeedRoute
  LauncherRoute: typeof LauncherRoute
  NewRoute: typeof NewRoute
  BoardsBoardIdRoute: typeof BoardsBoardIdRoute
  BotsBotIdRoute: typeof BotsBotIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  BoardsIndexRoute: typeof BoardsIndexRoute
  BotsIndexRoute: typeof BotsIndexRoute
  AppsServerIdToolRoute: typeof AppsServerIdToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher': {
      id: '/launcher'
      path: '/launcher'
      fullPath: '/launcher'
      preLoaderRoute: typeof LauncherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/': {
      id: '/bots/'
      path: '/bots'
      fullPath: '/bots/'
      preLoaderRoute: typeof BotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/': {
      id: '/boards/'
      path: '/boards'
      fullPath: '/boards/'
      preLoaderRoute: typeof BoardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/$botId': {
      id: '/bots/$botId'
      path: '/bots/$botId'
      fullPath: '/bots/$botId'
      preLoaderRoute: typeof BotsBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$serverId/$tool': {
      id: '/apps/$serverId/$tool'
      path: '/apps/$serverId/$tool'
      fullPath: '/apps/$serverId/$tool'
      preLoaderRoute: typeof AppsServerIdToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedRoute: FeedRoute,
  LauncherRoute: LauncherRoute,
  NewRoute: NewRoute,
  BoardsBoardIdRoute: BoardsBoardIdRoute,
  BotsBotIdRoute: BotsBotIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  BoardsIndexRoute: BoardsIndexRoute,
  BotsIndexRoute: BotsIndexRoute,
  AppsServerIdToolRoute: AppsServerIdToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
